---
title: "Test for overall randomness of plankton distribution"
author: "Thelma Panaïotis"
format: 
  html:
    toc: true
    embed-resources: true
editor: visual
lightbox: true
execute:
  warning: false
  cache: true
  freeze: false
---

```{r set_up}
#| echo: false
#| cache: false
source("utils.R")
```

Load computed distances

```{r read}
#| cache.lazy: false
load("data/03.all_distances.Rdata")
load("data/02a.f_val_dist.Rdata")
load("data/02b.rq_coef.Rdata")

# Apply log transformation for plotting
f_val_dist <- f_val_dist %>% 
  mutate(
    log_n_dist = log10(n_dist),
    log_test_stat = log10(test_stat)
  )

df_all <- df_all %>% 
    mutate(
    log_n_dist = log10(n_dist),
    log_test_stat = log10(test_stat)
  )
```

```{r plot_stat}
## Generate data to plot a ribbon between the regression lines
# limits for n_dist
lim_dist <- c(50, 2e9)
# Generate ribbon
rib_data <- tibble(n_dist = lim_dist) %>% 
  mutate(
    # apply log-transformation
    log_n_dist = log10(n_dist),
    # compute estimated kuiper-stat from slope and intercept
    ymin = rq_coef %>% filter(tau == 0.05) %>% pull(slope) * log_n_dist + rq_coef %>% filter(tau == 0.05) %>% pull(intercept),
    ymax = rq_coef %>% filter(tau == 0.95) %>% pull(slope) * log_n_dist + rq_coef %>% filter(tau == 0.95) %>% pull(intercept)
  ) %>% 
  # reformat and reorder to plot a polygon
  pivot_longer(ymin:ymax, values_to = "y") %>% 
  mutate(order = c(1, 2, 4, 3)) %>% 
  arrange(order)

## Plot results
ggplot() +
  geom_boxplot(data = f_val_dist, aes(x = log_n_dist, y = log_test_stat, group = log_n_dist), colour = "gray") +
  geom_polygon(data = rib_data, aes(x = log_n_dist, y = y), alpha = 0.1) +
  geom_point(data = df_all, aes(x = log_n_dist, y = log_test_stat), colour = "red") +
  scale_x_continuous(labels = label_math(expr = 10^.x, format = force), expand = c(0, 0)) +
  scale_y_continuous(labels = label_math(expr = 10^.x, format = force)) +
  labs(x = "N distances", y = "Kuiper statistic")

```

Plot distribution

```{r dist}
df_all %>% 
  dplyr::select(dist, dist_rand) %>% 
  unnest(c(dist, dist_rand)) %>% 
  pivot_longer(dist:dist_rand, names_to = "type", values_to = "dist") %>% 
  mutate(type = ifelse(type == "dist_rand", "rand", "data")) %>% 
  mutate(dist = dist * 51 / 10000) %>% # from pixel to cm
  ggplot() + 
  geom_density(aes(x = dist, colour = type), linewidth = 0.3) +
  scale_colour_manual(
    values = c("rand" = "grey20", "data" = "red"),
    labels = c("plankton", "null")
    ) +
  labs(x = "Distance (cm)", y = "Density", colour = "Type")
```

Plot ECDF.

```{r ecdf}
df_all %>% 
  dplyr::select(dist, dist_rand) %>% 
  unnest(c(dist, dist_rand)) %>% 
  pivot_longer(dist:dist_rand, names_to = "type", values_to = "dist") %>% 
  mutate(type = ifelse(type == "dist_rand", "rand", "data")) %>% 
  mutate(dist = dist * 51 / 10000) %>% # from pixel to cm
  ggplot() + 
  stat_ecdf(aes(x = dist, colour = type)) +
  scale_colour_manual(
    values = c("rand" = "grey20", "data" = "red"),
    labels = c("plankton", "null")
    ) +
  labs(x = "Distance (cm)")
```

::: {.callout-note icon="false"}
## Conclusion

**Distances between planktonic organisms at the local scale differ from the distances that could be expected if plankton was randomly distributed.**
:::

```{r}
df_all %>% 
  dplyr::select(dist, dist_rand) %>% 
  unnest(c(dist, dist_rand)) %>% 
  mutate(dist = dist * 51 / 10000) %>% # from pixel to cm
  ggplot() + 
  geom_density(aes(x = dist), colour = "#58C98E") +
  labs(x = "Distance (cm)", y = "Density")

df_all %>% 
  dplyr::select(dist, dist_rand) %>% 
  unnest(c(dist, dist_rand)) %>% 
  mutate(dist_rand = dist_rand * 51 / 10000) %>% # from pixel to cm
  ggplot() + 
  geom_density(aes(x = dist_rand), colour = "#50B1F9") +
  labs(x = "Distance (cm)", y = "Density")
```
