---
title: "Test for overall randomness of plankton distribution"
author: "Thelma Panaïotis"
format: 
  html:
    toc: true
    embed-resources: true
editor: visual
lightbox: true
execute:
  warning: false
  cache: true
  freeze: false
---

```{r set_up}
#| echo: false
#| cache: false
source("utils.R")
```

Load computed distances

```{r read}
#| cache.lazy: false
load("data/03.all_distances.Rdata")
```

Plot ECDF.

```{r ecdf}
df_all %>% 
  select(dist, dist_rand) %>% 
  unnest(c(dist, dist_rand)) %>% 
  pivot_longer(dist:dist_rand, names_to = "type", values_to = "dist") %>% 
  mutate(type = ifelse(type == "dist_rand", "rand", "data")) %>% 
  ggplot() + 
  stat_ecdf(aes(x = dist, colour = type))
```

Here is the result of the kuiper test.

```{r kuiper}
df_all$test_stat
df_all$p_value
```

::: {.callout-note icon="false"}
## Conclusion

**Distances between planktonic organisms at the local scale do not differ from the distances that could be expected if plankton was randomly distributed.**
:::
