---
title: "Analyze intrataxonomic distances."
author: "Thelma Panaïotis"
format: 
  html:
    toc: true
    embed-resources: true
editor: visual
lightbox: true
execute:
  warning: false
  cache: true
  freeze: false
---

```{r set_up}
#| cache: false
source("utils.R")
```

List saved distances and ream them

```{r load}
## Inter distances
# list processed files
processed <- list.files("data", pattern = "04.", full.names = TRUE)

# load data
res <- sapply(processed, function(x) mget(load(x)), simplify = TRUE)

# get summary data (1st line)
df_intra <- res[1,] %>% bind_rows()
# get distances (2nd line)
df_intra_dist <- res[2,] %>% bind_rows()

# Ignore colonial Collodaria
#df_inter <- df_inter %>% filter(!str_detect(pair, "Collodaria_colonial"))
#df_inter_dist <- df_inter_dist %>% filter(!str_detect(pair, "Collodaria_colonial"))

## Overall distances
load("data/03.all_distances.Rdata")
load("data/02.f_val_dist.Rdata")
```

Plot test stat

```{r}
df_intra %>% 
  ggplot() +
  geom_col(aes(x = taxon, y = test_stat, fill = n_obj)) +
  scale_fill_viridis_c(trans = "log10") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
#| fig-column: body-outset
#| out-width: 100%
ggplot() + 
  geom_boxplot(data = f_val_dist, aes(x = n_dist, y = test_stat, group = n_dist), colour = "gray") +
  geom_point(data = df_intra, aes(x = n_dist, y = test_stat, colour = taxon)) +
  scale_color_paletteer_d(`"khroma::discreterainbow"`) +
  scale_x_log10() + scale_y_log10()
```

Plot all distances.

```{r all_dist}
#| fig-column: screen-inset
#| out-width: 100%
#| fig-width: 12
#| fig-height: 5
df_intra_dist %>% 
  pivot_longer(dist:dist_rand) %>% 
  ggplot() +
  geom_density(aes(x = value, colour = name)) +
  facet_wrap(~taxon, scales = "free")
```

Plot all ECDF.

```{r all_ecdf}
#| fig-column: screen-inset
#| out-width: 100%
#| fig-width: 12
#| fig-height: 5
df_intra_dist %>% 
  pivot_longer(dist:dist_rand) %>% 
  ggplot() +
  stat_ecdf(aes(x = value, colour = name)) +
  facet_wrap(~taxon, scales = "free")
```
