---
title: "Analyze intrataxonomic distances."
author: "Thelma Panaïotis"
format: 
  html:
    toc: true
    embed-resources: true
editor: visual
lightbox: true
execute:
  warning: false
  cache: true
  freeze: false
---

```{r set_up}
#| cache: false
source("utils.R")
```

Load computed distances.

```{r load}
# Intrataxa
load("data/04.intra_distances.Rdata")

# Overall
load("data/02.all_distances.Rdata")

```

Plot test stat

```{r}
df_intra %>% 
  ggplot() +
  geom_col(aes(x = taxon, y = test_stat, fill = n_img)) +
  geom_hline(yintercept = df_all$test_stat, colour = "red") +
  scale_fill_viridis_c(trans = "log10") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
df_intra %>% 
  ggplot() +
  geom_col(aes(x = taxon, y = test_stat, fill = n_obj)) +
  geom_hline(yintercept = df_all$test_stat, colour = "red") +
  scale_fill_viridis_c(trans = "log10") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Have a look at Euchaeta.

```{r}
df <- df_intra_dist %>% 
  filter(taxon == "Mollusca") %>% 
  drop_na() %>% 
  pivot_longer(dist:dist_rand)
df %>% 
  ggplot() +
  geom_density(aes(x = value, colour = name))
df %>% 
  ggplot() +
  stat_ecdf(aes(x = value, colour = name))
```
